services:
    _defaults:
        autowire: true
        autoconfigure: true

    # controllers
    jalismrs_home.home_controller:
        arguments:
            $main: '%jalismrs_home.main%'
            $css: '%jalismrs_home.css%'
            $js: '%jalismrs_home.js%'
        calls:
            - setContainer:
                $container: '@Psr\Container\ContainerInterface'
        class: 'Jalismrs\Symfony\Bundle\JalismrsHomeBundle\Controller\HomeController'
        tags:
            - 'controller.service_arguments'
